/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  
    // main: [{type: 'autogenerated', dirName: '.'}], // for the root directory

    Overview: [{type: 'autogenerated', dirName: 'Overview'}], // for 'subdir1'
    Resources: [{type: 'autogenerated', dirName: 'resources'}], // for 'subdir1'
    Glossary: [{type: 'autogenerated', dirName: 'glossary'}], // for 'subdir2'
    Concepts: [{type: 'autogenerated', dirName: 'Concepts'}], // for 'subdir2'
    GLEIF: [{type: 'autogenerated', dirName: 'GLEIF'}], // for 'subdir1'
    Education: [{type: 'autogenerated', dirName: 'Education'}], // for 'subdir2'
    GLEIF: [{type: 'autogenerated', dirName: 'GLEIF'}], // for 'subdir1'
    Visualisations: [{type: 'autogenerated', dirName: 'Visualisations'}], // for 'subdir1'
    CarbonCopies: [{type: 'autogenerated', dirName: 'CarbonCopies'}], // for 'subdir1'
    Test: [{type: 'autogenerated', dirName: 'Test'}], // for 'subdir2'
    
    
    // add more directories as needed
  
  
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  HowWeDidSidebar: {
    Root:
      'How we did/intro',
      'How we did/why-terms-wot-manage-structure',
    Chat: [
      'How we did/Chatbots',
    ],
    Docusaurus: [
      'How we did/Docusaurus-process',
    ],
    Data: [
      'How we did/fill-out-terms-toip-wiki',
      'How we did/create-terms-link-table',
      'How we did/pull-changes-from-toip-to-terms',
      'How we did/embed-github-hosted-image-in-github-wiki-page',
      'How we did/sync-agenda-to-production-via-local',
    ],
    Terms: [
      'How we did/load-glossary-weboftrust-in-docusaurus',
      'How we did/markdown-from-WOT-wiki',
    ],
    Search: [
      'How we did/typesense-search-install-config',
      'How we did/Create-search-index',
    ],
    Label: [
      'How we did/label-content-and-alert-changes',
      'How we did/homepage-text-altering',
    ],
    Old: [
      'How we did/check-and-accept-PR-production-Edusite-locally',  // Old document
      'How we did/pull-in-markdown-documents',  // Old document
    ],
  },
};

module.exports = sidebars;
