/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Autogenerated sections
  main: [{type: 'autogenerated', dirName: '.'}],
  Overview: [{type: 'autogenerated', dirName: 'Overview'}],
  Resources: [{type: 'autogenerated', dirName: 'resources'}],
  Glossary: [{type: 'autogenerated', dirName: 'glossary'}],
  Concepts: [{type: 'autogenerated', dirName: 'Concepts'}],
  GLEIF: [{type: 'autogenerated', dirName: 'GLEIF'}],
  Education: [{type: 'autogenerated', dirName: 'Education'}],
  Visualisations: [{type: 'autogenerated', dirName: 'Visualisations'}],
  CarbonCopies: [{type: 'autogenerated', dirName: 'CarbonCopies'}],
  Test: [{type: 'autogenerated', dirName: 'Test'}],

  // Custom manual sidebar
  HowWeDidSidebar: [
      {
          type: 'category',
          label: 'Intro',
          items: [
              'How we did/intro',
              'How we did/why-terms-wot-manage-structure',
          ],
      },
      {
          type: 'category',
          label: 'Chat',
          items: [
              'How we did/Chatbots',
          ],
      },
      {
          type: 'category',
          label: 'Docusaurus',
          items: [
              'How we did/Docusaurus-process',
          ],
      },
      {
          type: 'category',
          label: 'Data',
          items: [
              'How we did/fill-out-terms-toip-wiki',
              'How we did/create-terms-link-table',
              'How we did/pull-changes-from-toip-to-terms',
              'How we did/embed-github-hosted-image-in-github-wiki-page',
              'How we did/sync-agenda-to-production-via-local',
          ],
      },
      {
          type: 'category',
          label: 'Terms',
          items: [
              'How we did/load-glossary-weboftrust-in-docusaurus',
              'How we did/markdown-from-WOT-wiki',
          ],
      },
      {
          type: 'category',
          label: 'Search',
          items: [
              'How we did/typesense-search-install-config',
              'How we did/Create-search-index',
          ],
      },
      {
          type: 'category',
          label: 'Label',
          items: [
              'How we did/label-content-and-alert-changes',
              'How we did/homepage-text-altering',
          ],
      },
      {
          type: 'category',
          label: 'Old',
          items: [
              'How we did/check-and-accept-PR-production-Edusite-locally',  // Old document
              'How we did/pull-in-markdown-documents',  // Old document
          ],
      },
  ],
};

module.exports = sidebars;
