/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  HowWeDidSidebar: {
    Root: [
      'How we did/intro',
      'How we did/why-terms-wot-manage-structure',
    ],
    Chat: [
      'How we did/Chatbots',
    ],
    Docusaurus: [
      'How we did/Docusaurus-process',
    ],
    Data: [
      'How we did/fill-out-terms-toip-wiki',
      'How we did/create-terms-link-table',
      'How we did/pull-changes-from-toip-to-terms',
      'How we did/embed-github-hosted-image-in-github-wiki-page',
      'How we did/sync-agenda-to-production-via-local',
    ],
    Glossary: [
      'How we did/load-glossary-weboftrust-in-docusaurus',
      'How we did/markdown-from-WOT-wiki',
    ],
    Search: [
      'How we did/typesense-search-install-config',
      'How we did/Create-search-index',
    ],
    Label: [
      'How we did/label-content-and-alert-changes',
      'How we did/homepage-text-altering',
    ],
    Old: [
      'How we did/check-and-accept-PR-production-Edusite-locally',  // Old document
      'How we did/pull-in-markdown-documents',  // Old document
    ],
  },
};

module.exports = sidebars;
