#!/bin/bash

node fetchExternalContent/fetchMentalModels/fetchToIPContent/fetchToIPContent.js

node fetchExternalContent/fetchMentalModels/fetchNistContent/fetchNistContent.mjs

node fetchExternalContent/fetchMentalModels/fetchEssifLabContent/fetchEssifLabContent.js

node fetchExternalContent/fetchMentalModels/fetchDigitalGovtNzContent/fetchDigitalGovtNzContent.js