name: Import all and Deploy to GitHub Pages

on:
  # A: Triggered on push to the main branch:
  # push:
  #   branches:
  #     - main

  # B: Triggered on manual workflow dispatch:
  workflow_dispatch:
  
  ## C: Triggered on Wiki changes:
  # gollum
jobs:
  call-action1:
    uses: ./import-wiki.yml

  call-action2:
    needs: call-action1
    uses: ./import-metadata-google-sheet.yml

  call-action3:
    needs: call-action2
    uses: ./import-external-glossaries.yml

  call-action4:
    needs: call-action3
    uses: ./deploy-to-gh-pages.yml
